### ISSUE TITLE
Provide configurable isVisible implementation setting

### ISSUE THREAD

**Issue by muuki88** [prebid/prebid-outstream#8]
This project currently ships it's own "is element visible" implementation, which is rather expensive in terms performance and not state of the art.

https://github.com/prebid/prebid-outstream/blob/dc959e02f357f4e7c8f07ce55d7d7bc49a869881/src/OutstreamPlayer.js#L75

There are alternatives like

- [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API)
- [gpt.js ImpressionViewableEvent](https://developers.google.com/publisher-tag/reference#googletag.events.impressionviewableevent)

which can be used as implementations.

It would be nice to either specify the "viewability" implementation 

1. at built time (shipping with the project)
2. or make it configurable at runtime. 

From a user perspective 1) would be awesome, but it requires maintenance for this project.

**Comment by timon-witt** [comment]
Hey, just wanted to share that I implemented this and will create a pull request in the future. Before doing so, I would like to test it in production however, which could take some time still.

**Comment by muuki88** [comment]
I guess so! I wasn't able to create a shiny release, because I'm still having trouble with #22 

However one can checkout `master` and it should work.
